#!/usr/bin/env bash

set -e

export PATH="\
$PWD/bin:\
$PWD/ext/bashplus/bin:\
$PWD/ext/test-more-bash/lib:\
$PWD/ext/test-more-bash/ext/test-tap-bash/lib:\
$PATH
"

source ext/bashplus/bin/bash+ :std
source lib/hither.bash

reset-env() {
  for e in `env`; do
    if [[ "$e" =~ ^HITHER_ ]]; then
      unset "${e%%=*}"
    fi
  done
}

assert-booktown-db() {
  if `! pg-db-exists booktown`; then
    RUN hither \
      --in=test/dataset/pg/booktown.sql \
      --out=pg://hither:h1th3r@localhost:5432/booktown
  fi
  if `! pg-db-exists booktown`; then
    die "Can't create booktown db"
  fi
}

FAIL=true
MERGE=false
SAY=false
CMD=run
RUN() {
  [ $# -gt 0 ] && local cmd=("$@") || local cmd=($CMD)
  if $SAY; then
    echo ">>> $cmd"
  fi
  retval=0
  if $MERGE; then
    stdout=$("${cmd[@]}" 2>&1) || retval=$?
    stderr=
  else
    local tmp=$(mktemp)
    stdout=$("${cmd[@]}" 2>$tmp) || retval=$?
    stderr=$(< $tmp)
    rm "$tmp"
  fi
  if [ $retval -ne 0 ]; then
    if $FAIL; then
      die "Command failed:"$'\n'"$stdout$stderr"
    else
      echo "$stdout$stderr" >&2
      return $retval
    fi
  fi
}

# vim: set sw=2:
