#!/usr/bin/env bash

set -e

export PATH="\
$PWD/bin:\
$PWD/ext/bashplus/bin:\
$PWD/ext/test-more-bash/lib:\
$PATH
"

source ext/bashplus/bin/bash+ :std
source lib/hither.bash

reset-env() {
  for e in `env`; do
    if [[ "$e" =~ ^HITHER_ ]]; then
      unset "${e%%=*}"
    fi
  done
}

assert-booktown-db() {
  if `! pg-db-exists booktown`; then
    RUN hither \
      --in=test/dataset/pg/booktown.sql \
      --out=pg://hither:h1th3r@localhost:5432/booktown
  fi
  if `! pg-db-exists booktown`; then
    die "Can't create booktown db"
  fi
}

# vim: set sw=2:
