#!/usr/bin/env bash

test_dir="$(dirname "$0")"
virtualenv_dir="$test_dir/django"
django_repo=hither-django-testing
django_project="${django_repo//-/_}"
django_app=data_viewer
django_dir="$virtualenv_dir/$django_project"

if [ "$1" == --RESET ]; then
  echo "# --RESET found: 'rm -fr $virtualenv_dir'"
  rm -fr "$virtualenv_dir"
fi

if [ ! -d "$virtualenv_dir" ]; then
  echo "# Making new virtualenv '$virtualenv_dir'"
  virtualenv "$virtualenv_dir" &>/dev/null
  echo "# Making new django project '$django_dir'"
  git clone \
    "git@github.com:ingydotnet/$django_repo" \
    "$django_dir" \
    &>/dev/null
fi

# Set up python env:
source $virtualenv_dir/bin/activate
(
  cd "$virtualenv_dir"

  if ! `which django-admin &>/dev/null`; then
    echo "# Installing django"
    pip install django &>/dev/null
    echo "# Installing pyyaml"
    pip install pyyaml &>/dev/null
  fi
)

cd "$django_dir"
git clean -dxf &>/dev/null

# vim: set ft=sh:
