#!/usr/bin/env bash

test_dir="$(dirname "$0")"
virtualenv_dir="$test_dir/django"
django_repo=hither-django-testing
django_project="${django_repo//-/_}"
django_app=data_viewer
django_dir="$virtualenv_dir/$django_project"

if [ "$1" == -R ]; then
  rm -fr "$virtualenv_dir"
fi

if [ ! -d "$virtualenv_dir" ]; then
  (
    virtualenv "$virtualenv_dir" &>/dev/null
    git clone \
      "git@github.com:ingydotnet/$django_repo" \
      "$django_dir"
  ) &>/dev/null
fi

# Set up python env:
(
  cd "$virtualenv_dir"

  source bin/activate
  if ! `which django-admin &>/dev/null`; then
    pip install django
    pip install pyyaml
  fi
) &>/dev/null
source $virtualenv_dir/bin/activate

cd "$django_dir"
git clean -dxf &>/dev/null

# vim: set ft=sh:
