#!/usr/bin/env bash

set -e

assert-booktown-db() {
  if `! pg-db-exists booktown`; then
    run() {
      hither \
          --in=test/devel/booktown.sql \
          --out=pg://hither:h1th3r@localhost:5432/booktown
    }; RUN
    (exit $retval) || diag "$stdout$stderr"
  fi
  if `! pg-db-exists booktown`; then
    die "Can't create booktown db"
  fi
}

# vim: set sw=2:
