#!/usr/bin/env bash

virtual_dir=django
django_dir="$virtual_dir/hither_django_testing"

if [ "$1" == -R ]; then
  rm -fr $virtual_dir
fi

if [ ! -d "$virtual_dir" ]; then
  virtualenv $virtual_dir
fi

if [ ! -d "$django_dir" ]; then
  git clone git@github.com:ingydotnet/hither-django-testing "$django_dir"
fi

# Set up python env:
(
set -e
  cd "$virtual_dir"

  source bin/activate
  if ! `which django-admin &>/dev/null`; then
    pip install django
    pip install pyyaml
  fi
) &> /dev/null
source $virtual_dir/bin/activate

cd "$django_dir"
git clean -dxf &> /dev/null

# vim: set ft=sh:
