#!/usr/bin/env bash

source "$(cd -P `dirname $BASH_SOURCE` && pwd -P)/../lib/hither.bash"

export HITHER_DJANGO_ADMIN_COMMAND=hitherpgtohsd
(
  set -o pipefail
  "$HITHER_LIB"/hither-cmd-pg-to-django | write-output
)

# vim: set ft=sh:
