#!/usr/bin/env bash

set -e

main() {
  local virtualenv=${1:?Directory name for Python virtualenv required}
  local django_project=hither
  local django_root=$virtualenv/$django_project/$django_project

  if [ ! -f "$virtualenv/bin/python" ]; then
    virtualenv $virtualenv &>/dev/null
  fi

  source $virtualenv/bin/activate

  django_admin_path=$(which django-admin 2>/dev/null) || true
  if [ -z "$django_admin_path" ] ||
     [[ ! "$django_admin_path" =~ $virtualenv ]]; then
    (
      pip install django
      pip install pyyaml
      pip install psycopg2
    ) &>/dev/null
  fi

  if [ ! -e $django_root ]; then
    (
      cd $virtualenv
      django-admin startproject $django_project
    ) &>/dev/null
  fi

  cp $(dirname $0)/../share/django-settings.py $django_root/settings.py
}

[ "$BASH_SOURCE" != "$0" ] || main "$@"

