#!/usr/bin/env perl
use strict; use warnings;
use File::Basename;
use lib dirname($0);
use Hither;

# Move logic common to hither-util-hsd-to-django into a Hither.pm
sub main {
  print uc read_input();
}

main();
