#!/usr/bin/env bash

set -e

source "$(cd -P `dirname $BASH_SOURCE` && pwd -P)/../lib/hither.bash"

[ -n "$HITHER_OUT_DBNAME" ] ||
  die "Command requires a database name"

if `pg-db-exists "$HITHER_OUT_DBNAME"`; then
  psql -c "drop database $HITHER_OUT_DBNAME" &>/dev/null || true
fi

psql -c "create database $HITHER_OUT_DBNAME"

read-input | psql $HITHER_OUT_DBNAME

# vim: set lisp ft=sh:
