#!/usr/bin/env bash

source "$(cd -P `dirname $BASH_SOURCE` && pwd -P)/hither.bash"

set-hither-vars-from-in-out-vars

django-run-command \
  python manage.py ${HITHER_DJANGO_ADMIN_COMMAND:-inspectdb}

# vim: set ft=sh:
