#!/usr/bin/env bash

source "$(cd -P `dirname $BASH_SOURCE` && pwd -P)/hither.bash"

for v in DBNAME HOST PORT USER PASSWORD; do
  hv=HITHER_$v iv=HITHER_IN_$v
  printf -v $hv ${!iv}
  export $hv
done

if [ -n "$HITHER_DJANGO_ROOT" ]; then
  hither_django_root=$HITHER_DJANGO_ROOT
  temp_dir=false
else
  hither_django_root=$(mktemp -d -t hither-django-XXXXXXXX)
  temp_dir=true
fi

hither-util-django-setup $hither_django_root

(
  cd $hither_django_root
  source ./bin/activate
  cd hither
  python manage.py inspectdb
)

if $temp_dir; then
  cat <<... >&2
This work was done in a Python virtualenv that needed to be set up and
configured. To reuse this environment, enter this line:

  export HITHER_DJANGO_ROOT="$hither_django_root"

...
fi

# vim: set ft=sh:
