#!/usr/bin/env bash

source bin/hither

DBNAME=booktown
DUMP_DIR=/tmp/dbicdump
NAMESPACE=TestSchema
PASSWORD=pa55w0rd
DBI=dbi:Pg

rm -fr $DUMP_DIR

if `! pg-db-exists $DBNAME`; then
  hither --in=test/devel/booktown.sql --to=pg
fi

dbicdump -o \
        dump_directory=$DUMP_DIR \
        $NAMESPACE \
        $DBI:database=$DBNAME \
        $USER $PASSWORD \
        &>/dev/null

perl -p -0e 's/^=\w(.*?\n)=cut\n\n?//gsm;' \
        -e 's/^#.*\n//gm;' \
        -e 's/\n+/\n/g;' \
        -e 's/use (utf8|warnings|strict);\n//g;' \
        -e 's/^1;//m;' \
        $DUMP_DIR/$NAMESPACE/Result/*
