#!/bin/bash

set -e

PATH="$PWD/bin:$PATH"
CWD="$(dirname $0)"
export HITHER_PROFILE=$CWD/pg-profile.sh

hither load \
  --in=http://www.commandprompt.com/ppbook/booktown.sql \
  --out=booktown.pg

rm -f booktown-1.hsd
hither make \
  --in=booktown.pg \
  --out=booktown-1.hsd

